import requests

session = requests.Session()
session.headers.update({
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
    'Accept-Language': 'en-IN,en;q=0.9',
})

# Candidate pool of real products across 5 stores
candidates = {
    "amazon": [
        {
            "title": "boAt Rockerz 558 Over Ear Headphones (50mm Drivers, 20H Battery)",
            "brand": "boAt",
            "category": "Audio",
            "product_url": "https://www.amazon.in/dp/B0BVRDWC9C",
            "image_url": "https://m.media-amazon.com/images/I/61L4SkS7w2L._SX679_.jpg",
            "price": 1999.0,
            "mrp": 4999.0,
            "rating": 4.3,
            "rating_count": 89400,
        },
        {
            "title": "boAt Bassheads 100 in-Ear Wired Headphones with Mic (Black)",
            "brand": "boAt",
            "category": "Audio",
            "product_url": "https://www.amazon.in/dp/B071Z8M4KX",
            "image_url": "https://m.media-amazon.com/images/I/513ugd16C6L._SX679_.jpg",
            "price": 399.0,
            "mrp": 999.0,
            "rating": 4.2,
            "rating_count": 342000,
        },
        {
            "title": "Fire-Boltt Ninja Call Pro Plus 1.83 Smartwatch with Bluetooth Calling",
            "brand": "Fire-Boltt",
            "category": "Wearables",
            "product_url": "https://www.amazon.in/dp/B0BF57RN3K",
            "image_url": "https://m.media-amazon.com/images/I/61AHiYyu3ZL._SX679_.jpg",
            "price": 1099.0,
            "mrp": 9999.0,
            "rating": 4.2,
            "rating_count": 78200,
        },
        {
            "title": "Red Tape Men Casual Clog Sliders with Slip-Resistant Sole",
            "brand": "Red Tape",
            "category": "Footwear",
            "product_url": "https://www.amazon.in/dp/B0CSWMZ4HM",
            "image_url": "https://m.media-amazon.com/images/I/71iRWRAU7FL._SY695_.jpg",
            "price": 569.0,
            "mrp": 2999.0,
            "rating": 4.2,
            "rating_count": 18400,
        },
        {
            "title": "boAt Rockerz 450 Bluetooth On-Ear Headphones with 15H Playback",
            "brand": "boAt",
            "category": "Audio",
            "product_url": "https://www.amazon.in/dp/B07PR1CL3S",
            "image_url": "https://m.media-amazon.com/images/I/51xxA+6E+xL._SX679_.jpg",
            "price": 1299.0,
            "mrp": 3990.0,
            "rating": 4.3,
            "rating_count": 115000,
        },
        {
            "title": "Samsung 45W Type-C Super Fast Travel Charger Adapter",
            "brand": "Samsung",
            "category": "Electronics",
            "product_url": "https://www.amazon.in/dp/B07V2BC91F",
            "image_url": "https://m.media-amazon.com/images/I/61bB+v8qJqL._SX679_.jpg",
            "price": 999.0,
            "mrp": 3499.0,
            "rating": 4.4,
            "rating_count": 12600,
        },
        {
            "title": "Portronics Glide Tilt Sensitive Stylus Pen for iPad",
            "brand": "Portronics",
            "category": "Electronics",
            "product_url": "https://www.amazon.in/dp/B0DF38F64P",
            "image_url": "https://m.media-amazon.com/images/I/51qtxqNKPML._SX679_.jpg",
            "price": 797.0,
            "mrp": 1999.0,
            "rating": 4.2,
            "rating_count": 3100,
        },
        {
            "title": "TheGiftKart Shockproof Crystal Clear Armor Case for Nothing Phone",
            "brand": "TheGiftKart",
            "category": "Accessories",
            "product_url": "https://www.amazon.in/dp/B0D79XDJ19",
            "image_url": "https://m.media-amazon.com/images/I/51Kn-xu2BUL._SX679_.jpg",
            "price": 299.0,
            "mrp": 999.0,
            "rating": 4.3,
            "rating_count": 4800,
        },
    ],
    "flipkart": [
        {
            "title": "Trendzino Men Ergonomic Acupressure Relaxation Flip-Flops",
            "brand": "Trendzino",
            "category": "Footwear",
            "product_url": "https://www.flipkart.com/trendzino-men-slippers/p/itmb5bc630167a00?pid=SFFGF5GYRPMZKP2P",
            "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/slipper-flip-flop/c/n/m/6-accupressure-slippers-1-size-6no-trendzino-multicolor-resized-original-imah3heud7quzauy.jpeg",
            "price": 135.0,
            "mrp": 499.0,
            "rating": 4.0,
            "rating_count": 8200,
        },
        {
            "title": "Wakefield Men Modern Anti-Skid Daily Casual Slippers",
            "brand": "Wakefield",
            "category": "Footwear",
            "product_url": "https://www.flipkart.com/wakefield-men-slippers/p/itmcaba0764d5968?pid=SFFGDZDXDS4BVZQN",
            "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/slipper-flip-flop/3/v/2/9-007-white-black-wakefield-white-black-resized-original-imah4kfzyjzhsrdr.jpeg",
            "price": 260.0,
            "mrp": 699.0,
            "rating": 4.1,
            "rating_count": 9800,
        },
        {
            "title": "FLITE Men Ultra-Soft Water-Resistant Everyday Comfort Slides",
            "brand": "FLITE",
            "category": "Footwear",
            "product_url": "https://www.flipkart.com/flite-men-slides/p/itme9d333c481aaa?pid=SFFHFUF2HTENUUGG",
            "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/slipper-flip-flop/j/g/l/9-whiite-flite-whiite-watermarked-original-imahfughawcwnawg.jpeg",
            "price": 319.0,
            "mrp": 549.0,
            "rating": 4.3,
            "rating_count": 48000,
        },
        {
            "title": "Portronics POR-372 Key2 Combo Wireless Keyboard & Mouse Set",
            "brand": "Portronics",
            "category": "Electronics",
            "product_url": "https://www.flipkart.com/portronics-por-372-key2-combo-wireless-keyboard-mouse-set-2-4-ghz-usb-receiver-laptop-size-laptop-compatible-desktop-laptop-mac-silent-keystrokes-1200-dpi-optical-tracking-multimedia-keys-pc/p/itm24a372eb918c8?pid=ACCFPNNCWBUUWJ7U",
            "image_url": "https://rukminim2.flixcart.com/image/832/832/xif0q/keyboard/laptop-keyboard/3/e/0/por-372-key2-wireless-keyboard-mouse-combo-portronics-enriched-transparent-original-imagj2heq84gcdz4.png",
            "price": 1049.0,
            "mrp": 1999.0,
            "rating": 4.2,
            "rating_count": 14200,
        },
    ],
    "myntra": [
        {
            "title": "BROADSTAR Men Relaxed Straight Leg Easy Wash Pleated Korean Pants",
            "brand": "BROADSTAR",
            "category": "Fashion",
            "product_url": "https://www.myntra.com/trousers/broadstar/broadstar-men-relaxed-straight-leg-straight-fit-easy-wash-pleated-korean-pants/36968033/buy",
            "image_url": "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/2025/SEPTEMBER/15/kwAmpR9a_e5ce9f1ae80a42a18a0b800355ee6680.jpg",
            "price": 989.0,
            "mrp": 1999.0,
            "rating": 4.3,
            "rating_count": 2700,
        },
        {
            "title": "BROADSTAR Men Smart Straight Fit Easy Wash Pleated Trousers",
            "brand": "BROADSTAR",
            "category": "Fashion",
            "product_url": "https://www.myntra.com/trousers/broadstar/broadstar-men-smart-straight-fit-easy-wash-pleated-trousers/38618666/buy",
            "image_url": "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/2025/DECEMBER/15/TMHSBRde_668dfa1d30474de8844d05ac5b7315dd.jpg",
            "price": 989.0,
            "mrp": 1999.0,
            "rating": 4.4,
            "rating_count": 3100,
        },
        {
            "title": "Koskii Women Floral Embroidered Thread Work Premium Dress Material",
            "brand": "Koskii",
            "category": "Fashion",
            "product_url": "https://www.myntra.com/trousers/broadstar/broadstar-men-relaxed-straight-leg-straight-fit-easy-wash-pleated-korean-pants/30855214/buy",
            "image_url": "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/2024/SEPTEMBER/4/6Il7NVwN_55f57a0ba9e342fb9a2ed0facda1d907.jpg",
            "price": 2490.0,
            "mrp": 4990.0,
            "rating": 4.4,
            "rating_count": 1900,
        },
        {
            "title": "HIGHLANDER Men Olive Green Slim Fit Solid Casual Cotton Shirt",
            "brand": "HIGHLANDER",
            "category": "Fashion",
            "product_url": "https://www.myntra.com/shirts/highlander/highlander-men-olive-green-slim-fit-casual-shirt/10356511/buy",
            "image_url": "https://assets.myntassets.com/h_720,q_90,w_540/v1/assets/images/10356511/2025/3/8/de31ac55-3742-4947-b32f-70f22ca038671741419318444-Libas-Women-Beige-Ethnic-Print-Straight-Kurta-Set-With-Side--1.jpg",
            "price": 549.0,
            "mrp": 1399.0,
            "rating": 4.1,
            "rating_count": 28400,
        },
    ],
    "nykaa": [
        {
            "title": "Vaseline Deep Moisture Body Lotion with Pro Ceramides For Dry Skin (600ml)",
            "brand": "Vaseline",
            "category": "Beauty",
            "product_url": "https://www.nykaa.com/vaseline-intensive-care-deep-restore-body-lotion/p/535502",
            "image_url": "https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/0/2/029e0788901030769443_1.jpg",
            "price": 468.0,
            "mrp": 850.0,
            "rating": 4.5,
            "rating_count": 21000,
        },
        {
            "title": "Nykaa Cosmetics Matte to Last Liquid Lipstick (5ml)",
            "brand": "Nykaa Cosmetics",
            "category": "Beauty",
            "product_url": "https://www.nykaa.com/nykaa-matte-to-last-liquid-lipstick/p/273398",
            "image_url": "https://images-static.nykaa.com/media/catalog/product/8/9/8904245704179_1.jpg",
            "price": 389.0,
            "mrp": 649.0,
            "rating": 4.4,
            "rating_count": 34500,
        },
    ],
    "ajio": [
        {
            "title": "POINT COVE Boys Patterned Relaxed Fit Pure Cotton Shirt",
            "brand": "POINT COVE",
            "category": "Fashion",
            "product_url": "https://www.ajio.com/point-cove-boys-patterned-relaxed-fit-shirt-with-patch-pocket/p/443666961_olive",
            "image_url": "https://assets.ajio.com/medias/sys_master/root1/20260312/fdWQ/69b2bc5a4970ce6a6e3efa1f/-473Wx593H-443666961-olive-MODEL.jpg",
            "price": 305.0,
            "mrp": 599.0,
            "rating": 4.3,
            "rating_count": 3800,
        },
    ]
}

print("Testing initial verified images...")
for store, items in candidates.items():
    print(f"\n--- {store.upper()} ---")
    for item in items:
        try:
            r = session.get(item['image_url'], stream=True, timeout=3)
            disc = round(((item['mrp'] - item['price']) / item['mrp']) * 100, 1)
            print(f"[{r.status_code}] {item['title'][:40]} | Rs {item['price']} (MRP Rs {item['mrp']}) - {disc}% OFF")
        except Exception as e:
            print(f"[ERR] {item['title'][:40]} | {e}")
