import React, { createContext, useContext, useState } from 'react';

export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    home: 'Home',
    deals: 'Deals',
    compare: 'Compare',
    alerts: 'Alerts',
    refer_win: 'Refer & win',
    theme: 'Theme',
    login: 'Log In',
    signup: 'Sign Up',
    dashboard: 'Dashboard',
    my_products: 'My Tracked Products',
    settings: 'Settings',
    logout: 'Log Out',
    hero_title: 'Never Overpay. Let PricePing Find the Right Price.',
    hero_subtitle: 'Compare prices, watch price history, and get alerted when it’s finally worth buying.',
    hero_placeholder: 'Search or paste any Amazon, Flipkart, Myntra, AJIO, Nykaa link...',
    find_best_price: 'Find Best Price',
    trending_deals: 'Trending Deals Across Stores',
    trending_subtitle: 'Real-time verified price drops across Amazon, Flipkart, Myntra, AJIO & Nykaa',
    live_verified: 'Live Verified Price Drops',
    track_price: 'Track Price',
    buy: 'Buy',
    delete: 'Delete',
    you_save: 'You save',
    cross_compare_title: 'Compare Stores in Real-Time',
    cross_compare_subtitle: 'Real-time pricing from all 5 e-commerces with verified stock availability',
    available: 'In Stock',
    not_available: 'Not Available',
    lowest_price: 'Lowest Price',
    free_delivery: 'Free Delivery',
    your_tracked_products: 'Your Tracked Products',
    track_new_product: 'Track New Product',
    active_scrapers: 'Active scrapers',
    watching_target: 'Watching target prices',
    triggered_drops: 'Triggered drops',
    ready_to_buy: 'Ready to buy',
    announcement_text: 'Track real-time price drops across Amazon, Flipkart, Myntra, AJIO & Nykaa.',
    explore_deals: 'Explore Deals',
  },
  hi: {
    home: 'होम',
    deals: 'ऑफ़र्स',
    compare: 'तुलना करें',
    alerts: 'अलर्ट्स',
    refer_win: 'रेफ़र और जीतें',
    theme: 'थीम',
    login: 'लॉग इन',
    signup: 'साइन अप',
    dashboard: 'डैशबोर्ड',
    my_products: 'मेरे ट्रैक किए गए उत्पाद',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    hero_title: '100+ स्टोर्स पर कीमतें तुलना करें और छूट ट्रैक करें',
    hero_subtitle: 'हर बार खरीदारी पर तुरंत बचत करें!',
    hero_placeholder: 'अमेज़न, फ्लिपकार्ट, मिंत्रा, अजियो या नायका का लिंक पेस्ट करें...',
    find_best_price: 'सर्वोत्तम मूल्य खोजें',
    trending_deals: 'सभी स्टोर्स पर ट्रेंडिंग डील्स',
    trending_subtitle: 'अमेज़न, फ्लिपकार्ट, मिंत्रा, अजियो और नायका से लाइव सत्यापित मूल्य गिरावट',
    live_verified: 'लाइव सत्यापित मूल्य गिरावट',
    track_price: 'कीमत ट्रैक करें',
    buy: 'खरीदें',
    delete: 'हटाएं',
    you_save: 'आपकी बचत',
    cross_compare_title: 'रियल-टाइम में स्टोर्स की तुलना करें',
    cross_compare_subtitle: 'सभी 5 ई-कॉमर्स साइट्स से लाइव कीमतें और वास्तविक उपलब्धता',
    available: 'उपलब्ध है',
    not_available: 'उपलब्ध नहीं है',
    lowest_price: 'सबसे कम कीमत',
    free_delivery: 'मुफ़्त डिलीवरी',
    your_tracked_products: 'आपके ट्रैक किए गए उत्पाद',
    track_new_product: 'नया उत्पाद ट्रैक करें',
    active_scrapers: 'सक्रिय ट्रैकर्स',
    watching_target: 'लक्ष्य कीमतें देख रहे हैं',
    triggered_drops: 'कम हुई कीमतें',
    ready_to_buy: 'खरीदने के लिए तैयार',
    announcement_text: 'अमेज़न, फ्लिपकार्ट, मिंत्रा, अजियो और नायका पर लाइव छूट ट्रैक करें।',
    explore_deals: 'ऑफ़र्स देखें',
  },
  bn: {
    home: 'হোম',
    deals: 'ডিলসমূহ',
    compare: 'তুলনা করুন',
    alerts: 'অ্যালার্ট',
    refer_win: 'রেফার এবং জিতুন',
    theme: 'থিম',
    login: 'লগ ইন',
    signup: 'সাইন আপ',
    dashboard: 'ড্যাশবোর্ড',
    my_products: 'আমার ট্র্যাক করা পণ্য',
    settings: 'সেটিংস',
    logout: 'লগ আউট',
    hero_title: '১০০+ স্টোরে মূল্য তুলনা করুন এবং অফার ট্র্যাক করুন',
    hero_subtitle: 'প্রতিটি কেনাকাটায় সাথে সাথে সাশ্রয় করুন!',
    hero_placeholder: 'অ্যামাজন, ফ্লিপকার্ট, মিন্ট্রা, অ্যাজিও বা নায়কার লিঙ্ক পেস্ট করুন...',
    find_best_price: 'সেরা মূল্য খুঁজুন',
    trending_deals: 'স্টোর জুড়ে ট্রেন্ডিং ডিল',
    trending_subtitle: 'অ্যামাজন, ফ্লিপকার্ট, মিন্ট্রা, অ্যাজিও ও নায়কা থেকে লাইভ ভেরিফায়েড ডিসকাউন্ট',
    live_verified: 'লাইভ যাচাইকৃত মূল্য হ্রাস',
    track_price: 'মূল্য ট্র্যাক করুন',
    buy: 'কিনুন',
    delete: 'মুছুন',
    you_save: 'আপনার সাশ্রয়',
    cross_compare_title: 'রিয়েল-টাইমে স্টোর তুলনা করুন',
    cross_compare_subtitle: 'সব ৫টি প্রধান ই-কমার্স থেকে লাইভ মূল্য এবং স্টক যাচাই',
    available: 'উপলব্ধ',
    not_available: 'উপলব্ধ নয়',
    lowest_price: 'সর্বনিম্ন মূল্য',
    free_delivery: 'ফ্রি ডেলিভারি',
    your_tracked_products: 'আপনার ট্র্যাক করা পণ্যসমূহ',
    track_new_product: 'নতুন পণ্য ট্র্যাক করুন',
    active_scrapers: 'সক্রিয় ট্র্যাকার',
    watching_target: 'টার্গেট প্রাইস পর্যবেক্ষণ চলছে',
    triggered_drops: 'মূল্য কমেছে',
    ready_to_buy: 'কেনার জন্য প্রস্তুত',
    announcement_text: 'অ্যামাজন, ফ্লিপকার্ট, মিন্ট্রা, অ্যাজিও ও নায়কায় লাইভ প্রাইস ড্রপ ট্র্যাক করুন।',
    explore_deals: 'ডিল দেখুন',
  },
  te: {
    home: 'హోమ్',
    deals: 'డీల్స్',
    compare: 'పోల్చండి',
    alerts: 'అలర్ట్‌లు',
    refer_win: 'రిఫర్ చేసి గెలవండి',
    theme: 'థీమ్',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    dashboard: 'డ్యాష్‌బోర్డ్',
    my_products: 'నా ఉత్పత్తులు',
    settings: 'సెట్టింగ్‌లు',
    logout: 'లాగ్ అవుట్',
    hero_title: '100+ స్టోర్లలో ధరలను పోల్చండి & ఆఫర్లను ట్రాక్ చేయండి',
    hero_subtitle: 'ప్రతి షాపింగ్‌లో వెంటనే ఆదా చేసుకోండి!',
    hero_placeholder: 'Amazon, Flipkart, Myntra, AJIO, Nykaa లింక్‌ను పేస్ట్ చేయండి...',
    find_best_price: 'ఉత్తమ ధరను కనుగొనండి',
    trending_deals: 'ట్రెండింగ్ డీల్స్',
    trending_subtitle: 'Amazon, Flipkart, Myntra, AJIO & Nykaa నుండి లైవ్ ఆఫర్లు',
    live_verified: 'లైవ్ ధృవీకరించబడిన ధర తగ్గింపులు',
    track_price: 'ధరను ట్రాక్ చేయండి',
    buy: 'కొనండి',
    delete: 'తొలగించు',
    you_save: 'మీరు ఆదా చేసినది',
    cross_compare_title: 'నిజ సమయంలో స్టోర్లను పోల్చండి',
    cross_compare_subtitle: 'అన్ని 5 ఇ-కామర్స్ సైట్ల నుండి ప్రత్యక్ష ధరలు',
    available: 'అందుబాటులో ఉంది',
    not_available: 'అందుబాటులో లేదు',
    lowest_price: 'అత్యల్ప ధర',
    free_delivery: 'ఉచిత డెలివరీ',
    your_tracked_products: 'మీరు ట్రాక్ చేసిన ఉత్పత్తులు',
    track_new_product: 'కొత్త ఉత్పత్తిని ట్రాక్ చేయండి',
    active_scrapers: 'యాక్టివ్ స్క్రాపర్లు',
    watching_target: 'టార్గెట్ ధరను పర్యవేక్షిస్తోంది',
    triggered_drops: 'తగ్గిన ధరలు',
    ready_to_buy: 'కొనడానికి సిద్ధంగా ఉంది',
    announcement_text: 'Amazon, Flipkart, Myntra, AJIO & Nykaa ధరల తగ్గింపును లైవ్ ట్రాక్ చేయండి.',
    explore_deals: 'డీల్స్ చూడండి',
  },
  ta: {
    home: 'முகப்பு',
    deals: 'சலுகைகள்',
    compare: 'ஒப்பிடுக',
    alerts: 'எச்சரிக்கைகள்',
    refer_win: 'பரிந்துரைத்து வெல்லுங்கள்',
    theme: 'தீம்',
    login: 'உள்நுழைக',
    signup: 'பதிவுசெய்க',
    dashboard: 'டாஷ்போர்டு',
    my_products: 'கண்காணிக்கப்படும் பொருட்கள்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறுக',
    hero_title: '100+ கடைகளில் விலைகளை ஒப்பிட்டு சலுகைகளை அறியுங்கள்',
    hero_subtitle: 'ஒவ்வொரு முறையும் வாங்கும் போதும் சேமித்திடுங்கள்!',
    hero_placeholder: 'Amazon, Flipkart, Myntra, AJIO, Nykaa இணைப்பை உள்ளிடவும்...',
    find_best_price: 'சிறந்த விலையைக் கண்டறிக',
    trending_deals: 'ட்ரெண்டிங் சலுகைகள்',
    trending_subtitle: 'Amazon, Flipkart, Myntra, AJIO & Nykaa நேரலை விலை குறைப்பு',
    live_verified: 'சரிபார்க்கப்பட்ட விலை வீழ்ச்சிகள்',
    track_price: 'விலையைக் கண்காணிக்கவும்',
    buy: 'வாங்கவும்',
    delete: 'நீக்கு',
    you_save: 'நீங்கள் சேமிப்பது',
    cross_compare_title: 'நேரலையில் கடைகளை ஒப்பிடுக',
    cross_compare_subtitle: '5 முன்னணி தளங்களின் நேரடி விலை மற்றும் இருப்பு விவரங்கள்',
    available: 'கிடைக்கிறது',
    not_available: 'கிடைக்கவில்லை',
    lowest_price: 'குறைந்தபட்ச விலை',
    free_delivery: 'இலவச டெலிவரி',
    your_tracked_products: 'உங்கள் பொருட்கள்',
    track_new_product: 'புதிய பொருளைக் கண்காணிக்கவும்',
    active_scrapers: 'செயலில் உள்ளவை',
    watching_target: 'இலக்கு விலை கண்காணிப்பு',
    triggered_drops: 'விலை சரிவுகள்',
    ready_to_buy: 'வாங்க தயாராக உள்ளது',
    announcement_text: 'Amazon, Flipkart, Myntra, AJIO & Nykaa ஆகியவற்றில் நேரலை விலை குறைப்பைக் கண்காணிக்கவும்.',
    explore_deals: 'சலுகைகளை ஆராய்க',
  },
  mr: {
    home: 'होम',
    deals: 'ऑफर्स',
    compare: 'तुलना करा',
    alerts: 'अलर्ट्स',
    refer_win: 'रेफर करा आणि जिंका',
    theme: 'थीम',
    login: 'लॉग इन',
    signup: 'साइन अप',
    dashboard: 'डॅशबोर्ड',
    my_products: 'ट्रॅक केलेली उत्पादने',
    settings: 'सेटिंग्ज',
    logout: 'लॉग आउट',
    hero_title: '100+ स्टोअर्सवर किमतींची तुलना करा आणि सूट मिळवा',
    hero_subtitle: 'प्रत्येक खरेदीवर त्वरित बचत करा!',
    hero_placeholder: 'Amazon, Flipkart, Myntra, AJIO, Nykaa लिंक पेस्ट करा...',
    find_best_price: 'सर्वोत्तम किंमत शोधा',
    trending_deals: 'ट्रेंडिंग डील्स',
    trending_subtitle: 'Amazon, Flipkart, Myntra, AJIO आणि Nykaa वरील लाइव्ह डिस्काउंट्स',
    live_verified: 'लाइव्ह सत्यापित किमतीतील घसरण',
    track_price: 'किंमत ट्रॅक करा',
    buy: 'खरेदी करा',
    delete: 'हटवा',
    you_save: 'तुमची बचत',
    cross_compare_title: 'रिअल-टाइममध्ये स्टोअर्सची तुलना करा',
    cross_compare_subtitle: 'सर्व 5 ई-कॉमर्स प्लॅटफॉर्मवरून थेट किमती आणि उपलब्धता',
    available: 'उपलब्ध आहे',
    not_available: 'उपलब्ध नाही',
    lowest_price: 'सर्वात कमी किंमत',
    free_delivery: 'मोफत डिलिव्हरी',
    your_tracked_products: 'तुमची ट्रॅक केलेली उत्पादने',
    track_new_product: 'नवीन उत्पादन ट्रॅक करा',
    active_scrapers: 'सक्रिय ट्रॅकर्स',
    watching_target: 'लक्ष्य किमतींचे निरीक्षण',
    triggered_drops: 'किंमत घसरण',
    ready_to_buy: 'खरेदीसाठी सज्ज',
    announcement_text: 'Amazon, Flipkart, Myntra, AJIO आणि Nykaa वरील रिअल-टाइम किंमत घसरण ट्रॅक करा.',
    explore_deals: 'ऑफर्स पहा',
  },
  gu: {
    home: 'હોમ',
    deals: 'ડીલ્સ',
    compare: 'સરખામણી કરો',
    alerts: 'એલર્ટ્સ',
    refer_win: 'રેફર કરો અને જીતો',
    theme: 'થીમ',
    login: 'લૉગ ઇન',
    signup: 'સાઇન અપ',
    dashboard: 'ડેશબોર્ડ',
    my_products: 'ટ્રૅક કરેલ પ્રોડક્ટ્સ',
    settings: 'સેટિંગ્સ',
    logout: 'લૉગ આઉટ',
    hero_title: '100+ સ્ટોર્સ પર કિંમતો સરખાવો અને ડિસ્કાઉન્ટ મેળવો',
    hero_subtitle: 'દરેક ખરીદી પર તાત્કાલિક બચત કરો!',
    hero_placeholder: 'Amazon, Flipkart, Myntra, AJIO, Nykaa ની લિંક અહીં પેસ્ટ કરો...',
    find_best_price: 'શ્રેષ્ઠ કિંમત શોધો',
    trending_deals: 'ટ્રેન્ડિંગ ડીલ્સ',
    trending_subtitle: 'Amazon, Flipkart, Myntra, AJIO અને Nykaa પરથી લાઇવ ડિસ્કાઉન્ટ',
    live_verified: 'લાઇવ ચકાસાયેલ ભાવ ઘટાડો',
    track_price: 'કિંમત ટ્રૅક કરો',
    buy: 'ખરીદો',
    delete: 'ડીલીટ કરો',
    you_save: 'તમારી બચત',
    cross_compare_title: 'રીયલ-ટાઇમમાં સ્ટોર્સ સરખાવો',
    cross_compare_subtitle: 'તમામ 5 મુખ્ય ઇ-કૉમર્સ સાઇટ્સ પરથી લાઇવ કિંમતો',
    available: 'ઉપલબ્ધ છે',
    not_available: 'ઉપલબ્ધ નથી',
    lowest_price: 'સૌથી ઓછી કિંમત',
    free_delivery: 'મફત ડિલિવરી',
    your_tracked_products: 'તમારી ટ્રૅક કરેલી પ્રોડક્ટ્સ',
    track_new_product: 'નવી પ્રોડક્ટ ટ્રૅક કરો',
    active_scrapers: 'સક્રિય સ્ક્રૅપર્સ',
    watching_target: 'ટાર્ગેટ કિંમત મોનિટરિંગ',
    triggered_drops: 'ઘટેલી કિંમતો',
    ready_to_buy: 'ખરીદવા માટે તૈયાર',
    announcement_text: 'Amazon, Flipkart, Myntra, AJIO અને Nykaa પર રીઅલ-ટાઇમ કિંમત ઘટાડો ટ્રૅક કરો.',
    explore_deals: 'ડીલ્સ જુઓ',
  },
  kn: {
    home: 'ಮುಖಪುಟ',
    deals: 'ಡೀಲ್‌ಗಳು',
    compare: 'ಹೋಲಿಸಿ',
    alerts: 'ಎಚ್ಚರಿಕೆಗಳು',
    refer_win: 'ರೆಫರ್ ಮಾಡಿ ಗೆಲ್ಲಿರಿ',
    theme: 'ಥೀಮ್',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    my_products: 'ನನ್ನ ಉತ್ಪನ್ನಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    hero_title: '100+ ಅಂಗಡಿಗಳಲ್ಲಿ ಬೆಲೆಗಳನ್ನು ಹೋಲಿಸಿ ಮತ್ತು ರಿಯಾಯಿತಿ ಪಡೆಯಿರಿ',
    hero_subtitle: 'ಪ್ರತಿ ಶಾಪಿಂಗ್‌ನಲ್ಲಿ ತಕ್ಷಣ ಉಳಿತಾಯ ಮಾಡಿ!',
    hero_placeholder: 'Amazon, Flipkart, Myntra, AJIO, Nykaa ಲಿಂಕ್ ನಮೂದಿಸಿ...',
    find_best_price: 'ಉತ್ತಮ ಬೆಲೆ ಹುಡುಕಿ',
    trending_deals: 'ಟ್ರೆಂಡಿಂಗ್ ಡೀಲ್‌ಗಳು',
    trending_subtitle: 'Amazon, Flipkart, Myntra, AJIO ಮತ್ತು Nykaa ಲೈವ್ ಬೆಲೆ ಇಳಿಕೆ',
    live_verified: 'ಲೈವ್ ಪರಿಶೀಲಿಸಿದ ಬೆಲೆ ಕುಸಿತಗಳು',
    track_price: 'ಬೆಲೆ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    buy: 'ಖರೀದಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    you_save: 'ನಿಮ್ಮ ಉಳಿತಾಯ',
    cross_compare_title: 'ನೈಜ ಸಮಯದಲ್ಲಿ ಅಂಗಡಿಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ',
    cross_compare_subtitle: 'ಎಲ್ಲಾ 5 ಪ್ರಮುಖ ಇ-ಕಾಮರ್ಸ್ ಸೈಟ್‌ಗಳಿಂದ ನೇರ ಬೆಲೆಗಳು',
    available: 'ಲಭ್ಯವಿದೆ',
    not_available: 'ಲಭ್ಯವಿಲ್ಲ',
    lowest_price: 'ಕನಿಷ್ಠ ಬೆಲೆ',
    free_delivery: 'ಉಚಿತ ವಿತರಣೆ',
    your_tracked_products: 'ನೀವು ಟ್ರ್ಯಾಕ್ ಮಾಡಿದ ಉತ್ಪನ್ನಗಳು',
    track_new_product: 'ಹೊಸ ಉತ್ಪನ್ನ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    active_scrapers: 'ಸಕ್ರಿಯ ಟ್ರ್ಯಾಕರ್‌ಗಳು',
    watching_target: 'ಗುರಿ ಬೆಲೆ ವೀಕ್ಷಣೆ',
    triggered_drops: 'ಬೆಲೆ ಇಳಿಕೆಗಳು',
    ready_to_buy: 'ಖರೀದಿಸಲು ಸಿದ್ಧ',
    announcement_text: 'Amazon, Flipkart, Myntra, AJIO ಮತ್ತು Nykaa ನಲ್ಲಿ ಲೈವ್ ಬೆಲೆ ಕುಸಿತವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
    explore_deals: 'ಡೀಲ್‌ಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
  },
  ml: {
    home: 'ഹോം',
    deals: 'ഡീലുകൾ',
    compare: 'താരതമ്യം',
    alerts: 'അലേർട്ടുകൾ',
    refer_win: 'റഫർ ചെയ്ത് നേടുക',
    theme: 'തീം',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    my_products: 'ട്രാക്ക് ചെയ്തവ',
    settings: 'ക്രമീകരണങ്ങൾ',
    logout: 'ലോഗ് ഔട്ട്',
    hero_title: '100+ സ്റ്റോറുകളിൽ വില താരതമ്യം ചെയ്ത് ലാഭിക്കൂ',
    hero_subtitle: 'ഓരോ പർച്ചേസിലും തൽക്ഷണം പണം ലാഭിക്കാം!',
    hero_placeholder: 'Amazon, Flipkart, Myntra, AJIO, Nykaa ലിങ്ക് നൽകുക...',
    find_best_price: 'മികച്ച വില കണ്ടെത്തൂ',
    trending_deals: 'ട്രെൻഡിംഗ് ഓഫറുകൾ',
    trending_subtitle: 'Amazon, Flipkart, Myntra, AJIO, Nykaa ലൈവ് വിലക്കുറവ്',
    live_verified: 'ലൈവ് പരിശോധിച്ച വിലയിടിവ്',
    track_price: 'വില ട്രാക്ക് ചെയ്യുക',
    buy: 'വാങ്ങുക',
    delete: 'നീക്കം ചെയ്യുക',
    you_save: 'നിങ്ങളുടെ ലാഭം',
    cross_compare_title: 'തത്സമയം സ്റ്റോറുകൾ താരതമ്യം ചെയ്യുക',
    cross_compare_subtitle: '5 പ്രധാന ഇ-കൊമേഴ്‌സ് പ്ലാറ്റ്‌ഫോമുകളിൽ നിന്നുള്ള ലൈവ് വിലകൾ',
    available: 'ലഭ്യമാണ്',
    not_available: 'ലഭ്യമല്ല',
    lowest_price: 'ഏറ്റവും കുറഞ്ഞ വില',
    free_delivery: 'സൗജന്യ ഡെലിവറി',
    your_tracked_products: 'നിങ്ങൾ ട്രാക്ക് ചെയ്യുന്നവ',
    track_new_product: 'പുതിയ ഉൽപ്പന്നം ട്രാക്ക് ചെയ്യുക',
    active_scrapers: 'ആക്ടീവ് ട്രാക്കറുകൾ',
    watching_target: 'ടാർഗെറ്റ് വില നിരീക്ഷിക്കുന്നു',
    triggered_drops: 'വില കുറഞ്ഞവ',
    ready_to_buy: 'വാങ്ങാൻ റെഡി',
    announcement_text: 'Amazon, Flipkart, Myntra, AJIO, Nykaa എന്നിവയിലെ ലൈവ് വിലക്കുറവ് ട്രാക്ക് ചെയ്യൂ.',
    explore_deals: 'ഡീലുകൾ കാണുക',
  },
  pa: {
    home: 'ਘਰ',
    deals: 'ਆਫ਼ਰਜ਼',
    compare: 'ਮੁਕਾਬਲਾ ਕਰੋ',
    alerts: 'ਅਲਰਟ',
    refer_win: 'ਰੈਫਰ ਕਰੋ ਅਤੇ ਜਿੱਤੋ',
    theme: 'ਥੀਮ',
    login: 'ਲਾਗ ਇਨ',
    signup: 'ਸਾਈਨ ਅੱਪ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    my_products: 'ਮੇਰੇ ਉਤਪਾਦ',
    settings: 'ਸੈਟਿੰਗਜ਼',
    logout: 'ਲਾਗ ਆਊਟ',
    hero_title: '100+ ਸਟੋਰਾਂ \'ਤੇ ਕੀਮਤਾਂ ਦੀ ਤੁਲਨਾ ਕਰੋ ਅਤੇ ਬੱਚਤ ਕਰੋ',
    hero_subtitle: 'ਹਰ ਖਰੀਦਦਾਰੀ \'ਤੇ ਤੁਰੰਤ ਪੈਸੇ ਬਚਾਓ!',
    hero_placeholder: 'Amazon, Flipkart, Myntra, AJIO, Nykaa ਲਿੰਕ ਪੇਸਟ ਕਰੋ...',
    find_best_price: 'ਸਭ ਤੋਂ ਵਧੀਆ ਕੀਮਤ ਲੱਭੋ',
    trending_deals: 'ਟ੍ਰੈਂਡਿੰਗ ਡੀਲਜ਼',
    trending_subtitle: 'Amazon, Flipkart, Myntra, AJIO ਅਤੇ Nykaa ਤੋਂ ਲਾਈਵ ਛੋਟ',
    live_verified: 'ਲਾਈਵ ਪ੍ਰਮਾਣਿਤ ਕੀਮਤ ਗਿਰਾਵਟ',
    track_price: 'ਕੀਮਤ ਟਰੈਕ ਕਰੋ',
    buy: 'ਖਰੀਦੋ',
    delete: 'ਹਟਾਓ',
    you_save: 'ਤੁਹਾਡੀ ਬੱਚਤ',
    cross_compare_title: 'ਅਸਲ ਸਮੇਂ ਵਿੱਚ ਸਟੋਰਾਂ ਦੀ ਤੁਲਨਾ ਕਰੋ',
    cross_compare_subtitle: 'ਸਾਰੇ 5 ਈ-ਕਾਮਰਸ ਸਟੋਰਾਂ ਤੋਂ ਲਾਈਵ ਰੇਟ',
    available: 'ਉਪਲਬਧ ਹੈ',
    not_available: 'ਉਪਲਬਧ ਨਹੀਂ',
    lowest_price: 'ਸਭ ਤੋਂ ਘੱਟ ਕੀਮਤ',
    free_delivery: 'ਮੁਫ਼ਤ ਡਿਲੀਵਰੀ',
    your_tracked_products: 'ਤੁਹਾਡੇ ਟਰੈਕ ਕੀਤੇ ਉਤਪਾਦ',
    track_new_product: 'ਨਵਾਂ ਉਤਪਾਦ ਟਰੈਕ ਕਰੋ',
    active_scrapers: 'ਐਕਟਿਵ ਟਰੈਕਰ',
    watching_target: 'ਨਿਸ਼ਾਨਾ ਕੀਮਤ ਨਿਗਰਾਨੀ',
    triggered_drops: 'ਘਟੀਆਂ ਕੀਮਤਾਂ',
    ready_to_buy: 'ਖਰੀਦਣ ਲਈ ਤਿਆਰ',
    announcement_text: 'Amazon, Flipkart, Myntra, AJIO ਅਤੇ Nykaa \'ਤੇ ਲਾਈਵ ਕੀਮਤ ਡਰਾਪ ਟਰੈਕ ਕਰੋ।',
    explore_deals: 'ਆਫ਼ਰ ਦੇਖੋ',
  },
};

interface LanguageContextType {
  currentLang: string;
  setLanguage: (code: string) => void;
  t: (key: string, fallback?: string) => string;
  currentOption: LanguageOption;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [currentLang, setCurrentLangState] = useState<string>(() => {
    return localStorage.getItem('priceping_language') || 'en';
  });

  const setLanguage = (code: string) => {
    setCurrentLangState(code);
    localStorage.setItem('priceping_language', code);

    // Support standard Google Translate cookie so full DOM translates if script is active
    document.cookie = `googtrans=/en/${code}; path=/;`;
    document.cookie = `googtrans=/en/${code}; path=/; domain=${window.location.hostname};`;
  };

  const currentOption = SUPPORTED_LANGUAGES.find((l) => l.code === currentLang) || SUPPORTED_LANGUAGES[0];

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[currentLang];
    if (langDict && langDict[key]) {
      return langDict[key];
    }
    const enDict = TRANSLATIONS.en;
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, currentOption }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
